In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
import statsmodels.api as sm
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
df = pd.read_csv('RegressionData_Master675.csv')
df.head()

Scenario  CirculatingNurse_Count  PreOpNurse_Count  MaintenanceGroup_Count  \
0         1                       5                 3                       3   
1         2                       4                 3                       3   
2         3                       3                 3                       3   
3         4                       2                 3                       3   
4         5                       1                 3                       3   

   ScrubNurse_Count  PACUNurse_Count     Overtime     Earnings  Cases bad?  
0                 5                3   193.047177  67496.11290     24  NaN  
1                 5                3   193.047177  68696.11290     24  NaN  
2                 5                3   193.047177  69896.11290     24  NaN  
3                 5                3   205.788424  70586.46305     24  NaN  
4                 5                3  1860.000000    197.00000     23    y

In [7]:
x = df[['CirculatingNurse_Count', 'PreOpNurse_Count', 'MaintenanceGroup_Count', 'ScrubNurse_Count', 'PACUNurse_Count']]
x = np.array(x)
y = np.array(df['Earnings'])
train_features, test_features, train_labels, test_labels = train_test_split(x, y, test_size=0.15, random_state=42)
rf = RandomForestRegressor(n_estimators=100, random_state=42) #100 trees in the forest 
rf.fit(x,y)
predictions = rf.predict(test_features)
rf.score(train_features, train_labels)

0.9984901910797417

In [3]:
bigArray = []
for a in (1,2,3,4,5):
    for b in (1,2,3):
        for c in (1,2,3):
            for d in (1,2,3,4,5):
                for e in (1,2,3):
                    smallArray = [a,b,c,d,e]
                    bigArray.append(smallArray)
                    
bigNP = np.array(bigArray)
earnings = rf.predict(bigNP)
indices = np.argsort(earnings) #sorts earnings from smallest to largest

for i in indices[-10:]: #calls the last 10 (largest) earnings 
    print(bigNP[i], earnings[i]) #and their indices 

[3 1 3 2 1] 77350.00198280002
[2 2 3 2 1] 77507.82234609997
[3 1 2 2 2] 77708.60256400007
[2 1 3 2 2] 77802.2978876001
[3 1 2 2 1] 78191.67260560003
[2 2 2 2 1] 78206.17583849998
[2 1 2 3 1] 78414.46329860008
[2 1 2 2 2] 78465.80451800009
[2 1 3 2 1] 79021.13972070008
[2 1 2 2 1] 79705.0125109001


In [50]:
bigNP

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 2],
       [1, 1, 1, 1, 3],
       ...,
       [5, 3, 3, 5, 1],
       [5, 3, 3, 5, 2],
       [5, 3, 3, 5, 3]])